// file name: mock-data.js
export const categories = [
  { id: 1, name: "POD T-Shirts", type: "pod" },
  { id: 2, name: "POD Sweatshirt", type: "pod" },
  { id: 3, name: "POD Hoodies", type: "pod" },
  { id: 4, name: "POD Mugs", type: "pod" },
  { id: 5, name: "POD Flags", type: "pod" },
  { id: 6, name: "Handmade T-Shirts", type: "handmade" },
  { id: 7, name: "Handmade Sweatshirt", type: "handmade" },
  { id: 8, name: "Handmade Hoodies", type: "handmade" },
  { id: 9, name: "Handmade Hats", type: "handmade" },
  { id: 10, name: "Handmade Flags", type: "handmade" },
];

export const products = [
  {
    id: 1,
    name: "Liberty Eagle POD T-Shirt",
    price: 24.99,
    oldPrice: 29.99,
    categoryId: 1,
    type: "pod",
    stock: 120,
    featured: true,
    colors: ["Red", "Yellow", "Purple"],
    image: "assets/images/products/p1.jpg",
    images: [
      "assets/images/products/p1.jpg",
      "assets/images/products/p1-1.jpg",
      "assets/images/products/p1-2.jpg",
      "assets/images/products/p1-3.jpg",
      "assets/images/products/p1-4.jpg",
      "assets/images/products/p1-5.jpg",
    ],
    description:
      "Soft cotton POD T-shirt with liberty eagle design for the US market.",
  },
  {
    id: 2,
    name: "Vintage Route 66 POD T-Shirt",
    price: 22.99,
    oldPrice: 27.99,
    categoryId: 1,
    type: "pod",
    stock: 95,
    featured: true,
    image: "assets/images/products/p2.jpg",
    images: [
      "assets/images/products/p2.jpg",
      "assets/images/products/p2-1.jpg",
      "assets/images/products/p2-2.jpg",
      "assets/images/products/p2-3.jpg",
    ],
    description:
      "Classic POD T-shirt inspired by the iconic Route 66 lifestyle.",
  },
  {
    id: 3,
    name: "Freedom Stars POD T-Shirt",
    price: 23.5,
    oldPrice: 28.5,
    categoryId: 1,
    type: "pod",
    stock: 100,
    featured: false,
    image: "assets/images/products/p3.jpg",
    images: [
      "assets/images/products/p3.jpg",
      "assets/images/products/p3-1.jpg",
      "assets/images/products/p3-2.jpg",
      "assets/images/products/p3-3.jpg",
    ],
    description: "Comfortable POD T-shirt with patriotic stars print.",
  },
  {
    id: 4,
    name: "USA Spirit POD T-Shirt",
    price: 25.99,
    oldPrice: 30.99,
    categoryId: 1,
    type: "pod",
    stock: 88,
    featured: false,
    image: "assets/images/products/p4.jpg",
    images: [
      "assets/images/products/p4.jpg",
      "assets/images/products/p4-1.jpg",
      "assets/images/products/p4-2.jpg",
      "assets/images/products/p4-3.jpg",
    ],
    description: "Modern POD T-shirt with USA spirit typography.",
  },
  {
    id: 5,
    name: "Minimal Flag POD T-Shirt",
    price: 21.99,
    oldPrice: 26.99,
    categoryId: 1,
    type: "pod",
    stock: 140,
    featured: true,
    image: "assets/images/products/p5.jpg",
    images: [
      "assets/images/products/p5.jpg",
      "assets/images/products/p5-1.jpg",
      "assets/images/products/p5-2.jpg",
      "assets/images/products/p5-3.jpg",
    ],
    description: "Minimal style POD T-shirt featuring a subtle US flag print.",
  },

  {
    id: 6,
    name: "Cozy Print POD Sweatshirt",
    price: 34.99,
    oldPrice: 39.99,
    categoryId: 2,
    type: "pod",
    stock: 80,
    featured: true,
    image: "assets/images/products/p6.jpg",
    images: [
      "assets/images/products/p6.jpg",
      "assets/images/products/p6-1.jpg",
      "assets/images/products/p6-2.jpg",
      "assets/images/products/p6-3.jpg",
    ],
    description: "Warm and cozy POD sweatshirt for casual everyday wear.",
  },
  {
    id: 7,
    name: "American Dream POD Sweatshirt",
    price: 36.99,
    oldPrice: 41.99,
    categoryId: 2,
    type: "pod",
    stock: 76,
    featured: false,
    image: "assets/images/products/p7.jpg",
    images: [
      "assets/images/products/p7.jpg",
      "assets/images/products/p7-1.jpg",
      "assets/images/products/p7-2.jpg",
      "assets/images/products/p7-3.jpg",
    ],
    description: "Premium POD sweatshirt with American dream graphic.",
  },
  {
    id: 8,
    name: "Mountain Camp POD Sweatshirt",
    price: 35.5,
    oldPrice: 40.5,
    categoryId: 2,
    type: "pod",
    stock: 64,
    featured: false,
    image: "assets/images/products/p8.jpg",
    images: [
      "assets/images/products/p8.jpg",
      "assets/images/products/p8-1.jpg",
      "assets/images/products/p8-2.jpg",
      "assets/images/products/p8-3.jpg",
    ],
    description: "Outdoor-inspired POD sweatshirt with mountain camp artwork.",
  },
  {
    id: 9,
    name: "Retro College POD Sweatshirt",
    price: 33.99,
    oldPrice: 38.99,
    categoryId: 2,
    type: "pod",
    stock: 90,
    featured: true,
    image: "assets/images/products/p9.jpg",
    images: [
      "assets/images/products/p9.jpg",
      "assets/images/products/p9-1.jpg",
      "assets/images/products/p9-2.jpg",
      "assets/images/products/p9-3.jpg",
    ],
    description:
      "Retro college style POD sweatshirt with soft fleece interior.",
  },
  {
    id: 10,
    name: "Patriot Badge POD Sweatshirt",
    price: 37.99,
    oldPrice: 42.99,
    categoryId: 2,
    type: "pod",
    stock: 55,
    featured: false,
    image: "assets/images/products/p10.jpg",
    images: [
      "assets/images/products/p10.jpg",
      "assets/images/products/p10-1.jpg",
      "assets/images/products/p10-2.jpg",
      "assets/images/products/p10-3.jpg",
    ],
    description: "POD sweatshirt featuring a bold patriot badge print.",
  },

  {
    id: 11,
    name: "Classic Street POD Hoodie",
    price: 44.99,
    oldPrice: 49.99,
    categoryId: 3,
    type: "pod",
    stock: 70,
    featured: true,
    image: "assets/images/products/p11.jpg",
    images: [
      "assets/images/products/p11.jpg",
      "assets/images/products/p11-1.jpg",
      "assets/images/products/p11-2.jpg",
      "assets/images/products/p11-3.jpg",
    ],
    description:
      "Streetwear-inspired POD hoodie with front pocket and soft lining.",
  },
  {
    id: 12,
    name: "Freedom Wolf POD Hoodie",
    price: 46.99,
    oldPrice: 51.99,
    categoryId: 3,
    type: "pod",
    stock: 60,
    featured: false,
    image: "assets/images/products/p12.jpg",
    images: [
      "assets/images/products/p12.jpg",
      "assets/images/products/p12-1.jpg",
      "assets/images/products/p12-2.jpg",
      "assets/images/products/p12-3.jpg",
    ],
    description: "Powerful wolf artwork POD hoodie for bold everyday style.",
  },
  {
    id: 13,
    name: "Sunset Road POD Hoodie",
    price: 43.5,
    oldPrice: 48.5,
    categoryId: 3,
    type: "pod",
    stock: 68,
    featured: false,
    image: "assets/images/products/p13.jpg",
    images: [
      "assets/images/products/p13.jpg",
      "assets/images/products/p13-1.jpg",
      "assets/images/products/p13-2.jpg",
      "assets/images/products/p13-3.jpg",
    ],
    description:
      "Relaxed fit POD hoodie inspired by sunset highway adventures.",
  },
  {
    id: 14,
    name: "Vintage USA POD Hoodie",
    price: 45.99,
    oldPrice: 50.99,
    categoryId: 3,
    type: "pod",
    stock: 72,
    featured: true,
    image: "assets/images/products/p14.jpg",
    images: [
      "assets/images/products/p14.jpg",
      "assets/images/products/p14-1.jpg",
      "assets/images/products/p14-2.jpg",
      "assets/images/products/p14-3.jpg",
    ],
    description: "Vintage washed POD hoodie with classic USA typography.",
  },
  {
    id: 15,
    name: "Urban Flag POD Hoodie",
    price: 47.5,
    oldPrice: 52.5,
    categoryId: 3,
    type: "pod",
    stock: 49,
    featured: false,
    image: "assets/images/products/p15.jpg",
    images: [
      "assets/images/products/p15.jpg",
      "assets/images/products/p15-1.jpg",
      "assets/images/products/p15-2.jpg",
      "assets/images/products/p15-3.jpg",
    ],
    description:
      "Urban style POD hoodie featuring a modern flag-inspired design.",
  },

  {
    id: 16,
    name: "Morning Quote POD Mug",
    price: 14.99,
    oldPrice: 18.99,
    categoryId: 4,
    type: "pod",
    stock: 150,
    featured: true,
    image: "assets/images/products/p16.jpg",
    images: [
      "assets/images/products/p16.jpg",
      "assets/images/products/p16-1.jpg",
      "assets/images/products/p16-2.jpg",
      "assets/images/products/p16-3.jpg",
    ],
    description: "Ceramic POD mug with a cheerful morning quote.",
  },
  {
    id: 17,
    name: "Patriot Coffee POD Mug",
    price: 15.99,
    oldPrice: 19.99,
    categoryId: 4,
    type: "pod",
    stock: 135,
    featured: false,
    image: "assets/images/products/p17.jpg",
    images: [
      "assets/images/products/p17.jpg",
      "assets/images/products/p17-1.jpg",
      "assets/images/products/p17-2.jpg",
      "assets/images/products/p17-3.jpg",
    ],
    description: "High-quality POD mug designed for coffee lovers.",
  },
  {
    id: 18,
    name: "Freedom Brew POD Mug",
    price: 13.99,
    oldPrice: 17.99,
    categoryId: 4,
    type: "pod",
    stock: 180,
    featured: false,
    image: "assets/images/products/p18.jpg",
    images: [
      "assets/images/products/p18.jpg",
      "assets/images/products/p18-1.jpg",
      "assets/images/products/p18-2.jpg",
      "assets/images/products/p18-3.jpg",
    ],
    description: "Simple and clean POD mug with freedom-inspired graphics.",
  },
  {
    id: 19,
    name: "Vintage Flag POD Mug",
    price: 16.5,
    oldPrice: 20.5,
    categoryId: 4,
    type: "pod",
    stock: 120,
    featured: true,
    image: "assets/images/products/p19.jpg",
    images: [
      "assets/images/products/p19.jpg",
      "assets/images/products/p19-1.jpg",
      "assets/images/products/p19-2.jpg",
      "assets/images/products/p19-3.jpg",
    ],
    description: "Vintage style POD mug with flag illustration.",
  },
  {
    id: 20,
    name: "Minimal Stars POD Mug",
    price: 14.5,
    oldPrice: 18.5,
    categoryId: 4,
    type: "pod",
    stock: 165,
    featured: false,
    image: "assets/images/products/p20.jpg",
    images: [
      "assets/images/products/p20.jpg",
      "assets/images/products/p20-1.jpg",
      "assets/images/products/p20-2.jpg",
      "assets/images/products/p20-3.jpg",
    ],
    description: "Minimal ceramic POD mug with star-themed print.",
  },

  {
    id: 21,
    name: "Outdoor Pride POD Flag",
    price: 19.99,
    oldPrice: 24.99,
    categoryId: 5,
    type: "pod",
    stock: 110,
    featured: true,
    image: "assets/images/products/p21.jpg",
    images: [
      "assets/images/products/p21.jpg",
      "assets/images/products/p21-1.jpg",
      "assets/images/products/p21-2.jpg",
      "assets/images/products/p21-3.jpg",
    ],
    description: "Durable POD flag suitable for indoor and outdoor decoration.",
  },
  {
    id: 22,
    name: "Liberty Print POD Flag",
    price: 21.99,
    oldPrice: 26.99,
    categoryId: 5,
    type: "pod",
    stock: 90,
    featured: false,
    image: "assets/images/products/p22.jpg",
    images: [
      "assets/images/products/p22.jpg",
      "assets/images/products/p22-1.jpg",
      "assets/images/products/p22-2.jpg",
      "assets/images/products/p22-3.jpg",
    ],
    description: "Printed POD flag with liberty-themed artwork.",
  },
  {
    id: 23,
    name: "Patriotic Home POD Flag",
    price: 18.99,
    oldPrice: 23.99,
    categoryId: 5,
    type: "pod",
    stock: 105,
    featured: false,
    image: "assets/images/products/p23.jpg",
    images: [
      "assets/images/products/p23.jpg",
      "assets/images/products/p23-1.jpg",
      "assets/images/products/p23-2.jpg",
      "assets/images/products/p23-3.jpg",
    ],
    description: "Decorative POD flag perfect for patriotic home display.",
  },
  {
    id: 24,
    name: "Vintage USA POD Flag",
    price: 22.5,
    oldPrice: 27.5,
    categoryId: 5,
    type: "pod",
    stock: 85,
    featured: true,
    image: "assets/images/products/p24.jpg",
    images: [
      "assets/images/products/p24.jpg",
      "assets/images/products/p24-1.jpg",
      "assets/images/products/p24-2.jpg",
      "assets/images/products/p24-3.jpg",
    ],
    description: "Vintage-style POD flag with premium fabric finish.",
  },
  {
    id: 25,
    name: "Stars and Freedom POD Flag",
    price: 20.5,
    oldPrice: 25.5,
    categoryId: 5,
    type: "pod",
    stock: 100,
    featured: false,
    image: "assets/images/products/p25.jpg",
    images: [
      "assets/images/products/p25.jpg",
      "assets/images/products/p25-1.jpg",
      "assets/images/products/p25-2.jpg",
      "assets/images/products/p25-3.jpg",
    ],
    description: "Eye-catching POD flag with stars and freedom symbol.",
  },

  {
    id: 26,
    name: "Handmade Cotton Embroidered T-Shirt",
    price: 29.99,
    oldPrice: 34.99,
    categoryId: 6,
    type: "handmade",
    stock: 25,
    featured: true,
    image: "assets/images/products/p26.jpg",
    images: [
      "assets/images/products/p26.jpg",
      "assets/images/products/p26-1.jpg",
      "assets/images/products/p26-2.jpg",
      "assets/images/products/p26-3.jpg",
    ],
    description: "Handmade cotton T-shirt with delicate embroidered details.",
  },
  {
    id: 27,
    name: "Artisan Floral Handmade T-Shirt",
    price: 31.99,
    oldPrice: 36.99,
    categoryId: 6,
    type: "handmade",
    stock: 18,
    featured: false,
    image: "assets/images/products/p27.jpg",
    images: [
      "assets/images/products/p27.jpg",
      "assets/images/products/p27-1.jpg",
      "assets/images/products/p27-2.jpg",
      "assets/images/products/p27-3.jpg",
    ],
    description: "Floral handmade T-shirt crafted with care and unique design.",
  },
  {
    id: 28,
    name: "Boho Stitch Handmade T-Shirt",
    price: 28.5,
    oldPrice: 33.5,
    categoryId: 6,
    type: "handmade",
    stock: 22,
    featured: false,
    image: "assets/images/products/p28.jpg",
    images: [
      "assets/images/products/p28.jpg",
      "assets/images/products/p28-1.jpg",
      "assets/images/products/p28-2.jpg",
      "assets/images/products/p28-3.jpg",
    ],
    description: "Boho-inspired handmade T-shirt with decorative stitching.",
  },
  {
    id: 29,
    name: "Cozy Yarn Accent Handmade T-Shirt",
    price: 32.5,
    oldPrice: 37.5,
    categoryId: 6,
    type: "handmade",
    stock: 16,
    featured: true,
    image: "assets/images/products/p29.jpg",
    images: [
      "assets/images/products/p29.jpg",
      "assets/images/products/p29-1.jpg",
      "assets/images/products/p29-2.jpg",
      "assets/images/products/p29-3.jpg",
    ],
    description: "Soft handmade T-shirt highlighted with yarn accent details.",
  },
  {
    id: 30,
    name: "Minimal Craft Handmade T-Shirt",
    price: 27.99,
    oldPrice: 32.99,
    categoryId: 6,
    type: "handmade",
    stock: 20,
    featured: false,
    image: "assets/images/products/p30.jpg",
    images: [
      "assets/images/products/p30.jpg",
      "assets/images/products/p30-1.jpg",
      "assets/images/products/p30-2.jpg",
      "assets/images/products/p30-3.jpg",
    ],
    description: "Minimal handmade T-shirt for a simple and cozy style.",
  },

  {
    id: 31,
    name: "Warm Knit Handmade Sweatshirt",
    price: 42.99,
    oldPrice: 47.99,
    categoryId: 7,
    type: "handmade",
    stock: 14,
    featured: true,
    image: "assets/images/products/p31.jpg",
    images: [
      "assets/images/products/p31.jpg",
      "assets/images/products/p31-1.jpg",
      "assets/images/products/p31-2.jpg",
      "assets/images/products/p31-3.jpg",
    ],
    description: "Warm handmade sweatshirt created with soft knit details.",
  },
  {
    id: 32,
    name: "Cozy Winter Handmade Sweatshirt",
    price: 44.99,
    oldPrice: 49.99,
    categoryId: 7,
    type: "handmade",
    stock: 12,
    featured: false,
    image: "assets/images/products/p32.jpg",
    images: [
      "assets/images/products/p32.jpg",
      "assets/images/products/p32-1.jpg",
      "assets/images/products/p32-2.jpg",
      "assets/images/products/p32-3.jpg",
    ],
    description: "Comfortable handmade sweatshirt for winter styling.",
  },
  {
    id: 33,
    name: "Artisan Patch Handmade Sweatshirt",
    price: 45.5,
    oldPrice: 50.5,
    categoryId: 7,
    type: "handmade",
    stock: 10,
    featured: false,
    image: "assets/images/products/p33.jpg",
    images: [
      "assets/images/products/p33.jpg",
      "assets/images/products/p33-1.jpg",
      "assets/images/products/p33-2.jpg",
      "assets/images/products/p33-3.jpg",
    ],
    description: "Handmade sweatshirt with unique artisan patchwork details.",
  },
  {
    id: 34,
    name: "Soft Wool Blend Handmade Sweatshirt",
    price: 46.99,
    oldPrice: 51.99,
    categoryId: 7,
    type: "handmade",
    stock: 9,
    featured: true,
    image: "assets/images/products/p34.jpg",
    images: [
      "assets/images/products/p34.jpg",
      "assets/images/products/p34-1.jpg",
      "assets/images/products/p34-2.jpg",
      "assets/images/products/p34-3.jpg",
    ],
    description:
      "Premium handmade sweatshirt made from soft wool blend fabric.",
  },
  {
    id: 35,
    name: "Neutral Tone Handmade Sweatshirt",
    price: 43.5,
    oldPrice: 48.5,
    categoryId: 7,
    type: "handmade",
    stock: 11,
    featured: false,
    image: "assets/images/products/p35.jpg",
    images: [
      "assets/images/products/p35.jpg",
      "assets/images/products/p35-1.jpg",
      "assets/images/products/p35-2.jpg",
      "assets/images/products/p35-3.jpg",
    ],
    description:
      "Neutral tone handmade sweatshirt for clean and elegant outfits.",
  },

  {
    id: 36,
    name: "Chunky Knit Handmade Hoodie",
    price: 49.99,
    oldPrice: 54.99,
    categoryId: 8,
    type: "handmade",
    stock: 8,
    featured: true,
    image: "assets/images/products/p36.jpg",
    images: [
      "assets/images/products/p36.jpg",
      "assets/images/products/p36-1.jpg",
      "assets/images/products/p36-2.jpg",
      "assets/images/products/p36-3.jpg",
    ],
    description: "Chunky knit handmade hoodie designed for warmth and comfort.",
  },
  {
    id: 37,
    name: "Cozy Yarn Handmade Hoodie",
    price: 51.99,
    oldPrice: 56.99,
    categoryId: 8,
    type: "handmade",
    stock: 7,
    featured: false,
    image: "assets/images/products/p37.jpg",
    images: [
      "assets/images/products/p37.jpg",
      "assets/images/products/p37-1.jpg",
      "assets/images/products/p37-2.jpg",
      "assets/images/products/p37-3.jpg",
    ],
    description: "Handmade hoodie with cozy yarn texture and practical fit.",
  },
  {
    id: 38,
    name: "Winter Bloom Handmade Hoodie",
    price: 52.5,
    oldPrice: 57.5,
    categoryId: 8,
    type: "handmade",
    stock: 6,
    featured: false,
    image: "assets/images/products/p38.jpg",
    images: [
      "assets/images/products/p38.jpg",
      "assets/images/products/p38-1.jpg",
      "assets/images/products/p38-2.jpg",
      "assets/images/products/p38-3.jpg",
    ],
    description: "Handmade hoodie with subtle floral winter-inspired accents.",
  },
  {
    id: 39,
    name: "Soft Touch Handmade Hoodie",
    price: 50.5,
    oldPrice: 55.5,
    categoryId: 8,
    type: "handmade",
    stock: 8,
    featured: true,
    image: "assets/images/products/p39.jpg",
    images: [
      "assets/images/products/p39.jpg",
      "assets/images/products/p39-1.jpg",
      "assets/images/products/p39-2.jpg",
      "assets/images/products/p39-3.jpg",
    ],
    description: "Soft-touch handmade hoodie with a cozy premium finish.",
  },
  {
    id: 40,
    name: "Limited Artisan Handmade Hoodie",
    price: 54.99,
    oldPrice: 59.99,
    categoryId: 8,
    type: "handmade",
    stock: 5,
    featured: false,
    image: "assets/images/products/p40.jpg",
    images: [
      "assets/images/products/p40.jpg",
      "assets/images/products/p40-1.jpg",
      "assets/images/products/p40-2.jpg",
      "assets/images/products/p40-3.jpg",
    ],
    description: "Limited handmade hoodie crafted carefully in small quantity.",
  },

  {
    id: 41,
    name: "Classic Wool Handmade Hat",
    price: 19.99,
    oldPrice: 24.99,
    categoryId: 9,
    type: "handmade",
    stock: 30,
    featured: true,
    image: "assets/images/products/p41.jpg",
    images: [
      "assets/images/products/p41.jpg",
      "assets/images/products/p41-1.jpg",
      "assets/images/products/p41-2.jpg",
      "assets/images/products/p41-3.jpg",
    ],
    description: "Classic wool handmade hat for cozy and stylish cold days.",
  },
  {
    id: 42,
    name: "Winter Charm Handmade Hat",
    price: 21.99,
    oldPrice: 26.99,
    categoryId: 9,
    type: "handmade",
    stock: 24,
    featured: false,
    image: "assets/images/products/p42.jpg",
    images: [
      "assets/images/products/p42.jpg",
      "assets/images/products/p42-1.jpg",
      "assets/images/products/p42-2.jpg",
      "assets/images/products/p42-3.jpg",
    ],
    description: "Elegant handmade hat with winter charm details.",
  },
  {
    id: 43,
    name: "Braided Yarn Handmade Hat",
    price: 22.5,
    oldPrice: 27.5,
    categoryId: 9,
    type: "handmade",
    stock: 20,
    featured: false,
    image: "assets/images/products/p43.jpg",
    images: [
      "assets/images/products/p43.jpg",
      "assets/images/products/p43-1.jpg",
      "assets/images/products/p43-2.jpg",
      "assets/images/products/p43-3.jpg",
    ],
    description: "Handmade braided yarn hat with a lovely textured finish.",
  },
  {
    id: 44,
    name: "Soft Beige Handmade Hat",
    price: 18.99,
    oldPrice: 23.99,
    categoryId: 9,
    type: "handmade",
    stock: 28,
    featured: true,
    image: "assets/images/products/p44.jpg",
    images: [
      "assets/images/products/p44.jpg",
      "assets/images/products/p44-1.jpg",
      "assets/images/products/p44-2.jpg",
      "assets/images/products/p44-3.jpg",
    ],
    description: "Soft beige handmade hat perfect for minimal winter fashion.",
  },
  {
    id: 45,
    name: "Pom Pom Handmade Hat",
    price: 23.99,
    oldPrice: 28.99,
    categoryId: 9,
    type: "handmade",
    stock: 18,
    featured: false,
    image: "assets/images/products/p45.jpg",
    images: [
      "assets/images/products/p45.jpg",
      "assets/images/products/p45-1.jpg",
      "assets/images/products/p45-2.jpg",
      "assets/images/products/p45-3.jpg",
    ],
    description: "Cute handmade hat with pom pom detail and cozy fit.",
  },

  {
    id: 46,
    name: "Knitted Home Decor Handmade Flag",
    price: 26.99,
    oldPrice: 31.99,
    categoryId: 10,
    type: "handmade",
    stock: 15,
    featured: true,
    image: "assets/images/products/p46.jpg",
    images: [
      "assets/images/products/p46.jpg",
      "assets/images/products/p46-1.jpg",
      "assets/images/products/p46-2.jpg",
      "assets/images/products/p46-3.jpg",
    ],
    description: "Handmade knitted decorative flag for warm home styling.",
  },
  {
    id: 47,
    name: "Rustic Yarn Handmade Flag",
    price: 28.99,
    oldPrice: 33.99,
    categoryId: 10,
    type: "handmade",
    stock: 12,
    featured: false,
    image: "assets/images/products/p47.jpg",
    images: [
      "assets/images/products/p47.jpg",
      "assets/images/products/p47-1.jpg",
      "assets/images/products/p47-2.jpg",
      "assets/images/products/p47-3.jpg",
    ],
    description: "Rustic decorative handmade flag crafted from quality yarn.",
  },
  {
    id: 48,
    name: "Boho Wall Handmade Flag",
    price: 27.5,
    oldPrice: 32.5,
    categoryId: 10,
    type: "handmade",
    stock: 11,
    featured: false,
    image: "assets/images/products/p48.jpg",
    images: [
      "assets/images/products/p48.jpg",
      "assets/images/products/p48-1.jpg",
      "assets/images/products/p48-2.jpg",
      "assets/images/products/p48-3.jpg",
    ],
    description:
      "Boho style handmade flag for wall decoration and cozy spaces.",
  },
  {
    id: 49,
    name: "Soft Texture Handmade Flag",
    price: 29.99,
    oldPrice: 34.99,
    categoryId: 10,
    type: "handmade",
    stock: 10,
    featured: true,
    image: "assets/images/products/p49.jpg",
    images: [
      "assets/images/products/p49.jpg",
      "assets/images/products/p49-1.jpg",
      "assets/images/products/p49-2.jpg",
      "assets/images/products/p49-3.jpg",
    ],
    description:
      "Decorative handmade flag with soft texture and artisan finish.",
  },
  {
    id: 50,
    name: "Minimal Craft Handmade Flag",
    price: 25.99,
    oldPrice: 30.99,
    categoryId: 10,
    type: "handmade",
    stock: 14,
    featured: false,
    image: "assets/images/products/p50.jpg",
    images: [
      "assets/images/products/p50.jpg",
      "assets/images/products/p50-1.jpg",
      "assets/images/products/p50-2.jpg",
      "assets/images/products/p50-3.jpg",
    ],
    description: "Minimal handmade flag for simple and elegant decor.",
  },
];

export const users = [
  {
    id: 1,
    fullName: "Admin",
    email: "admin@gmail.com",
    password: "123456",
    role: "admin",
    status: "active",
  },
  {
    id: 2,
    fullName: "Demo User",
    email: "user@gmail.com",
    password: "123456",
    role: "customer",
    status: "active",
  },
];

export const carts = [];
export const orders = [];
